# pyrefly: ignore [missing-import]
from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from sqlalchemy.orm import Session
from pathlib import Path
from datetime import datetime

from app.core.database import get_db
from app.core.models import User, Prediction, NewsSubmission, ModelVersion, Report
from app.core.security import get_current_user

router = APIRouter()

class ReportRequest(BaseModel):
    report_type: str
    title: str

class ReportResponse(BaseModel):
    id: int
    report_type: str
    title: str
    file_path: str
    generated_at: str

class ReportListResponse(BaseModel):
    items: list[ReportResponse]
    total: int

@router.post("", response_model=ReportResponse, status_code=201)
def generate_report(
    payload: ReportRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> ReportResponse:
    # 1. Fetch current metrics for the report
    total_users = db.query(User).count()
    total_submissions = db.query(NewsSubmission).count()
    fake_count = db.query(Prediction).filter(Prediction.predicted_label == "fake").count()
    real_count = db.query(Prediction).filter(Prediction.predicted_label == "real").count()
    
    active_model = db.query(ModelVersion).filter(ModelVersion.is_active == True).first()
    model_name = active_model.model_name if active_model else "N/A"
    model_algo = active_model.algorithm if active_model else "N/A"
    model_acc = float(active_model.accuracy) * 100.0 if active_model and active_model.accuracy is not None else 0.0
    model_f1 = float(active_model.f1_score) * 100.0 if active_model and active_model.f1_score is not None else 0.0

    # 2. Build the report text content
    report_text = f"""==================================================
TRUTHLENS AI - DETAILED SYSTEM STATUS & ANALYTICS REPORT
==================================================
Report Title: {payload.title}
Generated At: {datetime.utcnow().isoformat()}Z
Generated By: {current_user.full_name} ({current_user.email})
Report Type: {payload.report_type}

--------------------------------------------------
1. USER & USAGE STATISTICS
--------------------------------------------------
Total Registered Users: {total_users}
Total News Submissions analyzed: {total_submissions}

--------------------------------------------------
2. PREDICTION CLASSIFICATION DISTRIBUTION
--------------------------------------------------
Total Fake News Detected: {fake_count}
Total Likely Real News Detected: {real_count}

Ratio: {fake_count} Fake / {real_count} Real 
(Fake news accounts for {fake_count / max(1, total_submissions) * 100.0:.2f}% of submissions)

--------------------------------------------------
3. ACTIVE PREDICTION ENGINE METRICS
--------------------------------------------------
Active Model Name: {model_name}
Algorithm Type: {model_algo}
Model Evaluation Accuracy: {model_acc:.2f}%
Model Evaluation F1 Score: {model_f1:.2f}%

==================================================
END OF REPORT
==================================================
"""

    # 3. Save to database first to get the ID
    report = Report(
        user_id=current_user.id,
        report_type=payload.report_type,
        title=payload.title,
        file_path="temp_path"  # Temporary placeholder
    )
    db.add(report)
    db.commit()
    db.refresh(report)

    # 4. Save report file content to disk
    reports_dir = Path("reports_files")
    reports_dir.mkdir(exist_ok=True)
    report_file = reports_dir / f"report_{report.id}.txt"
    with open(report_file, "w", encoding="utf-8") as f:
        f.write(report_text)

    # 5. Update correct file_path in DB
    report.file_path = str(report_file.as_posix())
    db.commit()
    db.refresh(report)

    return ReportResponse(
        id=int(report.id),
        report_type=report.report_type,
        title=report.title,
        file_path=report.file_path,
        generated_at=report.generated_at.isoformat() + "Z" if report.generated_at else ""
    )

@router.get("", response_model=ReportListResponse)
def list_reports(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> ReportListResponse:
    # Admin can see all, normal user sees only their own
    if current_user.role == "admin":
        reports = db.query(Report).order_by(Report.generated_at.desc()).all()
    else:
        reports = db.query(Report).filter(Report.user_id == current_user.id).order_by(Report.generated_at.desc()).all()
        
    items = []
    for r in reports:
        items.append(ReportResponse(
            id=int(r.id),
            report_type=r.report_type,
            title=r.title,
            file_path=r.file_path if r.file_path else "",
            generated_at=r.generated_at.isoformat() + "Z" if r.generated_at else ""
        ))
    return ReportListResponse(items=items, total=len(items))

@router.get("/{report_id}/content")
def get_report_content(
    report_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    report = db.query(Report).filter(Report.id == report_id).first()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found.")
        
    # Access control: only owner or admin can read content
    if current_user.role != "admin" and report.user_id != current_user.id:
        raise HTTPException(status_code=403, detail="Not authorized to access this report.")
        
    if not report.file_path:
        raise HTTPException(status_code=404, detail="Report file not generated.")
        
    report_path = Path(report.file_path)
    if not report_path.exists():
        raise HTTPException(status_code=404, detail="Report file not found on disk.")
        
    with open(report_path, "r", encoding="utf-8") as f:
        content = f.read()
        
    return {"content": content}
